config: !!python/object:ts3l.utils.scarf_utils.scarf_config.SCARFConfig
  backbone_config: !!python/object:ts3l.utils.backbone_utils.mlp_backbone_config.MLPBackboneConfig
    activation: ReLU
    dropout_rate: 0.3
    hidden_dims:
    - 128
    input_dim: 95
    n_hiddens: 2
    name: mlp
    output_dim: 128
    use_batch_norm: true
  corruption_rate: 0.6
  dropout_rate: 0.04
  embedding_config: !!python/object:ts3l.utils.embedding_utils.identity_config.IdentityEmbeddingConfig
    input_dim: 95
    name: identity
    output_dim: 95
  head_depth: 2
  initialization: kaiming_uniform
  loss_fn: CrossEntropyLoss
  loss_hparams: {}
  metric: accuracy_score
  metric_hparams: {}
  optim: AdamW
  optim_hparams:
    lr: 0.0001
    weight_decay: 5.0e-05
  output_dim: 2
  pretraining_head_dim: 1024
  random_seed: 42
  scheduler: null
  scheduler_hparams: null
  task: classification
  tau: 0.1
