config: !!python/object:ts3l.utils.switchtab_utils.switchtab_config.SwitchTabConfig
  alpha: 1.0
  backbone_config: !!python/object:ts3l.utils.backbone_utils.transformer_config.TransformerBackboneConfig
    d_model: 128
    dropout_rate: 0.3
    encoder_depth: 2
    ffn_factor: 2.0
    hidden_dim: 1024
    n_head: 2
    name: transformer
  corruption_rate: 0.3
  embedding_config: !!python/object:ts3l.utils.embedding_utils.feature_tokenizer_config.FTEmbeddingConfig
    cat_cardinality:
    - 7
    - 7
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 6
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 6
    - 6
    - 5
    - 5
    - 3
    - 4
    - 5
    - 7
    - 3
    - 4
    - 2
    - 3
    - 2
    - 2
    cont_nums: 54
    emb_dim: 128
    input_dim: 95
    name: feature_tokenizer
    output_dim: 95
    required_token_dim: 2
  initialization: kaiming_uniform
  loss_fn: CrossEntropyLoss
  loss_hparams: {}
  metric: roc_auc_score
  metric_hparams: {}
  optim: AdamW
  optim_hparams:
    lr: 0.0001
    weight_decay: 5.0e-05
  output_dim: 2
  random_seed: 123
  scheduler: null
  scheduler_hparams: null
  task: classification
  u_label: -1
